#!/usr/bin/env bash
# Installs these plugins into a Vencord checkout's src/userplugins.
#
#   ./install.sh [--copy|--link] [/path/to/Vencord]
#
# --copy (default) drops a plain copy into src/userplugins. Re-run it after you
#   edit anything in this repo.
# --link symlinks instead, so the repo stays the single source of truth. esbuild
#   resolves symlinks to their real path before it looks for tsconfig path
#   aliases, so this also writes a local (gitignored) tsconfig.json pointing at
#   your checkout - without it the build cannot resolve @utils/*, @webpack/* etc.

set -euo pipefail

PLUGINS=(callWrapped voiceQualityHUD replyGraph)
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="copy"
VENCORD=""

for arg in "$@"; do
    case "$arg" in
        --copy) MODE="copy" ;;
        --link) MODE="link" ;;
        -h|--help) sed -n '2,13p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) VENCORD="$arg" ;;
    esac
done

if [[ -z "$VENCORD" ]]; then
    for candidate in "$HOME/Vencord" "$HOME/vencord" "$REPO/../Vencord" "$REPO/../vencord"; do
        if [[ -d "$candidate/src/plugins" ]]; then
            VENCORD="$candidate"
            break
        fi
    done
fi

if [[ -z "$VENCORD" || ! -d "$VENCORD/src/plugins" ]]; then
    echo "Could not find a Vencord checkout. Pass one: ./install.sh /path/to/Vencord" >&2
    exit 1
fi

VENCORD="$(cd "$VENCORD" && pwd)"
TARGET="$VENCORD/src/userplugins"
mkdir -p "$TARGET"

for plugin in "${PLUGINS[@]}"; do
    rm -rf "${TARGET:?}/$plugin"
    if [[ "$MODE" == "link" ]]; then
        ln -s "$REPO/$plugin" "$TARGET/$plugin"
    else
        cp -R "$REPO/$plugin" "$TARGET/$plugin"
    fi
    echo "$MODE: $plugin -> $TARGET/$plugin"
done

if [[ "$MODE" == "link" ]]; then
    cat > "$REPO/tsconfig.json" <<EOF
{
    "//": "Generated by install.sh --link for $VENCORD. Machine specific, not committed.",
    "compilerOptions": {
        "baseUrl": ".",
        "jsx": "preserve",
        "paths": {
            "@main/*": ["$VENCORD/src/main/*"],
            "@api/*": ["$VENCORD/src/api/*"],
            "@components/*": ["$VENCORD/src/components/*"],
            "@debug/*": ["$VENCORD/src/debug/*"],
            "@utils/*": ["$VENCORD/src/utils/*"],
            "@plugins/*": ["$VENCORD/src/plugins/*"],
            "@shared/*": ["$VENCORD/src/shared/*"],
            "@webpack/common": ["$VENCORD/src/webpack/common"],
            "@webpack/common/*": ["$VENCORD/src/webpack/common/*"],
            "@webpack": ["$VENCORD/src/webpack/webpack"],
            "@webpack/types": ["$VENCORD/src/webpack/types"]
        }
    }
}
EOF
    echo "wrote $REPO/tsconfig.json for $VENCORD"
fi

echo
echo "Now build Vencord:"
echo "  cd $VENCORD && pnpm build"
echo "then restart Discord and enable the plugins in Settings > Plugins."
